[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.18" # to use a specific local solc install set the path as `solc = "<path to solc>/solc"`

[rpc_endpoints]
local = "http://127.0.0.1:8545"
mumbai = "https://endpoints.omniatech.io/v1/matic/mumbai/public"

[etherscan]
mumbai = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config